In [65]:
import os
import pandas as pd
import numpy as np

In [66]:
#set the path of the raw data
raw_folder_path = 'C:/Users/shedgep/DataScience/Covid/raw'
AgeGroupDetails_file_path = os.path.join(raw_folder_path,'AgeGroupDetails.csv')
HospitalBedsIndia_file_path = os.path.join(raw_folder_path,'HospitalBedsIndia.csv')
ICMRTestingLabs_file_path = os.path.join(raw_folder_path,'ICMRTestingLabs.csv')
IndividualDetails_file_path = os.path.join(raw_folder_path,'IndividualDetails.csv')
StatewiseTestingDetails_file_path = os.path.join(raw_folder_path,'StatewiseTestingDetails.csv')
covid_19_india_file_path = os.path.join(raw_folder_path,'covid_19_india.csv')
population_india_census2011_file_path = os.path.join(raw_folder_path,'population_india_census2011.csv')

In [67]:
#read the data with all default parameters
AgeGroupDetails_df = pd.read_csv(AgeGroupDetails_file_path, index_col='Sno')
HospitalBedsIndia_df = pd.read_csv(HospitalBedsIndia_file_path, index_col='Sno')
ICMRTestingLabs_df = pd.read_csv(ICMRTestingLabs_file_path, index_col='lab')
IndividualDetails_df = pd.read_csv(IndividualDetails_file_path, index_col='id')
StatewiseTestingDetails_df = pd.read_csv(StatewiseTestingDetails_file_path)
covid_19_india_df = pd.read_csv(covid_19_india_file_path, index_col='Sno')
population_india_census2011_df = pd.read_csv(population_india_census2011_file_path, index_col='Sno')

In [68]:
#Renaming column
covid_19_india_df = covid_19_india_df.rename(columns = {'State/UnionTerritory':'State'})
population_india_census2011_df = population_india_census2011_df.rename(columns = {'State / Union Territory':'State'})
HospitalBedsIndia_df = HospitalBedsIndia_df.rename(columns = {'State/UT':'State'})

In [81]:
#Changing date folrmat, sometime it was swaping day with month
#covid_19_india_df['Date'] = pd.to_datetime(covid_19_india_df['Date']).dt.strftime("%d/%m/%Y")
#StatewiseTestingDetails_df['Date'] = pd.to_datetime(StatewiseTestingDetails_df['Date']).dt.strftime("%d/%m/%Y")
#Its working fine as it format date with yyy-mm-dd
covid_19_india_df['Date'] = pd.to_datetime(covid_19_india_df.Date, dayfirst=True)
StatewiseTestingDetails_df['Date'] = pd.to_datetime(StatewiseTestingDetails_df.Date, dayfirst=True)

In [82]:
#Filter on column values
covid_19_india_df.loc[(covid_19_india_df['Date']== '2020-03-11') & (covid_19_india_df['State']=='Delhi')]

,Date,Time,State,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
Sno,,,,,,,,
99,2020-03-11,6:00 PM,Delhi,5,0,0,0,5

In [83]:
#Filter on column values
covid_19_india_df.loc[(covid_19_india_df['Date']== '2020-03-13') & (covid_19_india_df['State']=='Delhi')]

,Date,Time,State,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
Sno,,,,,,,,
123,2020-03-13,6:00 PM,Delhi,6,0,0,0,6

In [85]:
covid_19_india_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2522 entries, 1 to 2522
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      2522 non-null   datetime64[ns]
 1   Time                      2522 non-null   object
 2   State                     2522 non-null   object
 3   ConfirmedIndianNational   2522 non-null   object
 4   ConfirmedForeignNational  2522 non-null   object
 5   Cured                     2522 non-null   int64
 6   Deaths                    2522 non-null   int64
 7   Confirmed                 2522 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 177.3+ KB

In [86]:
StatewiseTestingDetails_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1574 entries, 0 to 1573
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          1574 non-null   datetime64[ns]
 1   State         1574 non-null   object
 2   TotalSamples  1574 non-null   float64
 3   Negative      1251 non-null   float64
 4   Positive      1566 non-null   float64
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 61.6+ KB

In [98]:
#Join the Dataframes on defined columns
main_df = covid_19_india_df.merge(StatewiseTestingDetails_df,how='left',left_on=['Date','State'],right_on=['Date','State'])
main_df = main_df.merge(population_india_census2011_df,how='left',left_on=['State'],right_on=['State'])
main_df = main_df.merge(HospitalBedsIndia_df,how='left',left_on=['State'],right_on=['State'])
#Sorting the values on State and Date
main_df = main_df.sort_values(["State","Date"], ascending=(True,True))
main_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2524 entries, 365 to 2522
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              2524 non-null   datetime64[ns]
 1   Time                              2524 non-null   object
 2   State                             2524 non-null   object
 3   ConfirmedIndianNational           2524 non-null   object
 4   ConfirmedForeignNational          2524 non-null   object
 5   Cured                             2524 non-null   int64
 6   Deaths                            2524 non-null   int64
 7   Confirmed                         2524 non-null   int64
 8   TotalSamples                      1475 non-null   float64
 9   Negative                          1155 non-null   float64
 10  Positive                          1467 non-null   float64
 11  Population                        2483 non-null   float64
 12  Rural population                  2483 non-null   float64
 13  Urban population                  2483 non-null   float64
 14  Area                              2483 non-null   object
 15  Density                           2483 non-null   object
 16  Gender Ratio                      2483 non-null   float64
 17  NumPrimaryHealthCenters_HMIS      2155 non-null   object
 18  NumCommunityHealthCenters_HMIS    2155 non-null   float64
 19  NumSubDistrictHospitals_HMIS      1943 non-null   float64
 20  NumDistrictHospitals_HMIS         2155 non-null   float64
 21  TotalPublicHealthFacilities_HMIS  2155 non-null   float64
 22  NumPublicBeds_HMIS                2155 non-null   float64
 23  NumRuralHospitals_NHP18           2155 non-null   float64
 24  NumRuralBeds_NHP18                2155 non-null   float64
 25  NumUrbanHospitals_NHP18           2155 non-null   float64
 26  NumUrbanBeds_NHP18                2155 non-null   float64
dtypes: datetime64[ns](1), float64(16), int64(3), object(7)
memory usage: 552.1+ KB

In [99]:
main_df.tail()

,Date,Time,State,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed,TotalSamples,Negative,...,NumPrimaryHealthCenters_HMIS,NumCommunityHealthCenters_HMIS,NumSubDistrictHospitals_HMIS,NumDistrictHospitals_HMIS,TotalPublicHealthFacilities_HMIS,NumPublicBeds_HMIS,NumRuralHospitals_NHP18,NumRuralBeds_NHP18,NumUrbanHospitals_NHP18,NumUrbanBeds_NHP18
2378,2020-05-27,8:00 AM,West Bengal,-,-,1486,283,4009,166513.0,NaN,...,1374,406.0,70.0,55.0,1905.0,51163.0,1272.0,19684.0,294.0,58882.0
2414,2020-05-28,8:00 AM,West Bengal,-,-,1578,289,4192,175769.0,NaN,...,1374,406.0,70.0,55.0,1905.0,51163.0,1272.0,19684.0,294.0,58882.0
2450,2020-05-29,8:00 AM,West Bengal,-,-,1578,289,4192,185051.0,NaN,...,1374,406.0,70.0,55.0,1905.0,51163.0,1272.0,19684.0,294.0,58882.0
2486,2020-05-30,8:00 AM,West Bengal,-,-,1775,302,4813,194397.0,NaN,...,1374,406.0,70.0,55.0,1905.0,51163.0,1272.0,19684.0,294.0,58882.0
2522,2020-05-31,8:00 AM,West Bengal,-,-,1970,309,5130,NaN,NaN,...,1374,406.0,70.0,55.0,1905.0,51163.0,1272.0,19684.0,294.0,58882.0

In [100]:
main_df.to_csv('C:/Users/shedgep/DataScience/Covid/processed\masterfile.csv', index=False)